# Generated by Django 6.0.7 on 2026-07-23 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120, verbose_name='nom')),
                ('categorie', models.CharField(choices=[('bijoux', 'Bijoux'), ('papeterie', 'Papeterie'), ('sacs', 'Sacs'), ('vetements', 'Vêtements')], max_length=20, verbose_name='catégorie')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='prix (€)')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='stock')),
                ('coup_de_coeur', models.BooleanField(default=False, verbose_name='coup de cœur')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
            ],
            options={
                'verbose_name': 'produit',
                'verbose_name_plural': 'produits',
                'ordering': ['categorie', 'nom'],
            },
        ),
    ]
