# Generated by Django 6.0.7 on 2026-07-23 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nom')),
                ('category', models.CharField(choices=[('jewelry', 'Bijoux'), ('stationery', 'Papeterie'), ('bags', 'Sacs'), ('clothing', 'Vêtements')], max_length=20, verbose_name='catégorie')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='prix (€)')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='stock')),
                ('featured', models.BooleanField(default=False, verbose_name='coup de cœur')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
            ],
            options={
                'verbose_name': 'produit',
                'verbose_name_plural': 'produits',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.DeleteModel(
            name='Produit',
        ),
    ]
