# Generated by Django 6.0.7 on 2026-07-24 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='image')),
                ('alt', models.CharField(max_length=200, verbose_name='texte alternatif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
            ],
            options={
                'verbose_name': 'photo de galerie',
                'verbose_name_plural': 'photos de galerie',
                'ordering': ['-created_at'],
            },
        ),
    ]
