# Generated by Django 6.0.7 on 2026-07-28 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_galleryphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpeningHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')], unique=True, verbose_name='jour')),
                ('opens_at', models.TimeField(blank=True, null=True, verbose_name='ouverture')),
                ('closes_at', models.TimeField(blank=True, null=True, verbose_name='fermeture')),
                ('closed', models.BooleanField(default=False, verbose_name='fermé')),
            ],
            options={
                'verbose_name': "horaire d'ouverture",
                'verbose_name_plural': "horaires d'ouverture",
                'ordering': ['day'],
            },
        ),
    ]
