# Generated by Django 6.0.7 on 2026-07-28 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_openinghours'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='stories/', verbose_name='image')),
                ('handle', models.CharField(max_length=100, verbose_name='légende / @handle')),
                ('link', models.URLField(verbose_name='lien Instagram')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="ordre d'affichage")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
            ],
            options={
                'verbose_name': 'story Instagram',
                'verbose_name_plural': 'stories Instagram',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
