# Generated by Django 6.0.7 on 2026-07-28 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_instagramstory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instagramstory',
            name='link',
        ),
    ]
