# Generated by Django 6.0.7 on 2026-07-28 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_remove_instagramstory_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='posts/', verbose_name='image')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='légende')),
                ('link', models.URLField(verbose_name='lien vers le post')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="ordre d'affichage")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
            ],
            options={
                'verbose_name': 'post Instagram',
                'verbose_name_plural': 'posts Instagram',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
