# Generated by Django 6.0.7 on 2026-07-30 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_instagrampost'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuDrink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nom')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='prix (€)')),
                ('category', models.CharField(choices=[('coffee', 'Coffee'), ('matcha', 'Matcha & more')], max_length=20, verbose_name='catégorie')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="ordre d'affichage")),
                ('available', models.BooleanField(default=True, verbose_name='disponible')),
            ],
            options={
                'verbose_name': 'boisson du menu',
                'verbose_name_plural': 'boissons du menu',
                'ordering': ['category', 'order'],
            },
        ),
    ]
