# Generated by Django 6.0.7 on 2026-07-30 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_menudrink'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrinkOfMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nom')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='prix (€)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="ordre d'affichage")),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
            ],
            options={
                'verbose_name': 'boisson du mois',
                'verbose_name_plural': 'boissons du mois',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
