# Generated by Django 6.0.7 on 2026-07-30 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_drinkofmonth'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrinkOfMonthSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_until', models.DateField(blank=True, null=True, verbose_name="disponibles jusqu'au")),
            ],
            options={
                'verbose_name': 'réglage des boissons du mois',
                'verbose_name_plural': 'réglages des boissons du mois',
            },
        ),
    ]
