# Generated by Django 6.0.7 on 2026-07-30 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_drinkofmonthsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200, verbose_name='libellé')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='prix (€)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="ordre d'affichage")),
                ('available', models.BooleanField(default=True, verbose_name='disponible')),
            ],
            options={
                'verbose_name': 'supplément',
                'verbose_name_plural': 'suppléments',
                'ordering': ['order'],
            },
        ),
    ]
