# Generated by Django 6.0.7 on 2026-08-04 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_supplement'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(blank=True, max_length=200, verbose_name='rue')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='code postal')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='ville')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='téléphone')),
                ('instagram_url', models.URLField(blank=True, verbose_name='lien Instagram')),
                ('tiktok_url', models.URLField(blank=True, verbose_name='lien TikTok')),
            ],
            options={
                'verbose_name': 'coordonnées du site',
                'verbose_name_plural': 'coordonnées du site',
            },
        ),
    ]
