# Generated by Django 6.0.7 on 2026-07-30 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_supplement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drinkofmonthsettings',
            options={'verbose_name': 'note « durée limitée »', 'verbose_name_plural': 'note « durée limitée »'},
        ),
    ]
