# Generated by Django 6.0.7 on 2026-08-06 13:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_alter_drinkofmonthsettings_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinkofmonth',
            name='order',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name="ordre d'affichage"),
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='order',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name="ordre d'affichage"),
        ),
        migrations.AlterField(
            model_name='instagramstory',
            name='order',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name="ordre d'affichage"),
        ),
        migrations.AlterField(
            model_name='menudrink',
            name='order',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name="ordre d'affichage"),
        ),
        migrations.AlterField(
            model_name='supplement',
            name='order',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name="ordre d'affichage"),
        ),
    ]
