# Generated by Django 6.0.7 on 2026-08-06 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_alter_drinkofmonthsettings_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinkofmonth',
            name='active',
            field=models.BooleanField(default=True, verbose_name='affichée sur le site'),
        ),
        migrations.AlterField(
            model_name='menudrink',
            name='available',
            field=models.BooleanField(default=True, verbose_name='affichée sur le site'),
        ),
        migrations.AlterField(
            model_name='supplement',
            name='available',
            field=models.BooleanField(default=True, verbose_name='affiché sur le site'),
        ),
    ]
