# Generated by Django 6.0.7 on 2026-08-06 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_alter_drinkofmonth_active_alter_menudrink_available_and_more'),
        ('catalog', '0016_alter_drinkofmonth_order_alter_instagrampost_order_and_more'),
    ]

    operations = [
    ]
