# Generated by Django 6.0.7 on 2026-08-28 07:47

from django.db import migrations, models
from django.utils.text import slugify


def remplir_les_slugs(apps, schema_editor):
    """Donne un slug à chaque produit déjà en base.

    On passe par apps.get_model() et non par un import direct : ça donne une
    version « historique » du modèle, figée à cette étape de la migration.
    Un import direct pointerait vers le modèle d'aujourd'hui, qui aura peut-être
    changé quand cette migration sera rejouée sur une base neuve — et là, ça
    casse. C'est la règle d'or des migrations de données.

    Noter aussi que Product.save() n'est PAS appelé ici (les migrations
    écrivent directement en base), d'où la logique d'unicité recopiée.
    """
    Product = apps.get_model("catalog", "Product")

    deja_pris = set()
    for produit in Product.objects.all():
        base = slugify(produit.name) or "produit"
        candidat = base
        compteur = 2
        while candidat in deja_pris:
            candidat = f"{base}-{compteur}"
            compteur += 1
        deja_pris.add(candidat)
        produit.slug = candidat
        produit.save(update_fields=["slug"])


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_merge_20260806_1718'),
    ]

    operations = [
        # 1. On ajoute la colonne SANS contrainte d'unicité : à ce stade tous
        #    les produits existants auraient le même slug vide, ce qui la
        #    violerait immédiatement.
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=140, verbose_name='identifiant URL'),
            preserve_default=False,
        ),
        # 2. On remplit les slugs, chacun différent.
        migrations.RunPython(
            remplir_les_slugs,
            # Le sens inverse (annuler la migration) n'a rien à faire :
            # la colonne entière disparaîtra de toute façon.
            migrations.RunPython.noop,
        ),
        # 3. Maintenant que les valeurs sont uniques, on peut poser la contrainte.
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=140, unique=True, verbose_name='identifiant URL'),
        ),
    ]
