# Generated by Django 6.0.7 on 2026-08-28 07:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_product_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/', verbose_name='image')),
                ('alt', models.CharField(blank=True, help_text="Décrit la photo pour les lecteurs d'écran. Si vide, le nom du produit est utilisé.", max_length=200, verbose_name='texte alternatif')),
                ('order', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name="ordre d'affichage")),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product', verbose_name='produit')),
            ],
            options={
                'verbose_name': 'photo du produit',
                'verbose_name_plural': 'photos du produit',
                'ordering': ['order', 'id'],
            },
        ),
    ]
