# Generated by Django 6.0.7 on 2026-08-28 08:50

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='free_shipping_from',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Laisser vide pour ne jamais offrir la livraison.', max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='livraison offerte à partir de (€)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='shipping_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.90'), help_text='Montant facturé pour une livraison à domicile.', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='frais de livraison (€)'),
        ),
    ]
