# Generated by Django 6.0.7 on 2026-08-28 08:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_sitesettings_free_shipping_from_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('first_name', models.CharField(max_length=80, verbose_name='prénom')),
                ('last_name', models.CharField(max_length=80, verbose_name='nom')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='téléphone')),
                ('delivery_method', models.CharField(choices=[('pickup', 'Retrait en boutique'), ('home', 'Livraison à domicile')], default='pickup', max_length=20, verbose_name='mode de livraison')),
                ('address_line1', models.CharField(blank=True, max_length=200, verbose_name='adresse')),
                ('address_line2', models.CharField(blank=True, max_length=200, verbose_name="complément d'adresse")),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='code postal')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='ville')),
                ('shipping_fee', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='frais de livraison (€)')),
                ('status', models.CharField(choices=[('pending', 'En attente de paiement'), ('paid', 'Payée'), ('shipped', 'Expédiée'), ('ready', 'Prête à retirer'), ('cancelled', 'Annulée')], default='pending', max_length=20, verbose_name='statut')),
                ('stripe_session_id', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='session Stripe')),
                ('notes', models.TextField(blank=True, help_text="Visible uniquement dans l'admin, jamais par le client.", verbose_name='note interne')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='passée le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifiée le')),
            ],
            options={
                'verbose_name': 'commande',
                'verbose_name_plural': 'commandes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=120, verbose_name='nom du produit')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='prix unitaire (€)')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='quantité')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalog.order', verbose_name='commande')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='catalog.product', verbose_name='produit')),
            ],
            options={
                'verbose_name': 'article commandé',
                'verbose_name_plural': 'articles commandés',
            },
        ),
    ]
