# Generated by Django 6.0.7 on 2026-08-28 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_order_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, help_text="Le nom officiel de l'entreprise, tel qu'il figure sur l'extrait Kbis (ex. « Chérie Cherry SARL »).", max_length=200, verbose_name='raison sociale')),
                ('legal_form', models.CharField(blank=True, help_text='Ex. SARL, SAS, EI, micro-entreprise.', max_length=100, verbose_name='forme juridique')),
                ('share_capital', models.CharField(blank=True, help_text='Le cas échéant, ex. « 5 000 € ». Laisser vide pour une entreprise individuelle.', max_length=50, verbose_name='capital social')),
                ('siret', models.CharField(blank=True, help_text='Les 14 chiffres, espaces autorisés.', max_length=20, verbose_name='SIRET')),
                ('vat_number', models.CharField(blank=True, help_text='Ex. FR12345678901. Laisser vide si non assujettie.', max_length=20, verbose_name='numéro de TVA intracommunautaire')),
                ('publication_director', models.CharField(blank=True, help_text='La personne responsable du contenu du site, en général la gérante.', max_length=120, verbose_name='directeur / directrice de la publication')),
                ('host_name', models.CharField(blank=True, help_text="L'entreprise qui héberge le site.", max_length=200, verbose_name="nom de l'hébergeur")),
                ('host_address', models.CharField(blank=True, max_length=250, verbose_name="adresse de l'hébergeur")),
                ('host_contact', models.CharField(blank=True, help_text="Téléphone ou site web de l'hébergeur.", max_length=200, verbose_name="contact de l'hébergeur")),
                ('dispatch_delay', models.CharField(blank=True, help_text='Sous combien de temps un colis part après le paiement (ex. « 3 jours ouvrés »).', max_length=100, verbose_name="délai d'expédition")),
                ('delivery_delay', models.CharField(blank=True, help_text='Temps de trajet indicatif après expédition (ex. « 2 à 5 jours ouvrés »).', max_length=100, verbose_name='délai de livraison')),
                ('pickup_delay', models.CharField(blank=True, help_text='Combien de temps une commande est gardée en magasin (ex. « 14 jours »).', max_length=100, verbose_name='délai de retrait en boutique')),
                ('mediator', models.TextField(blank=True, help_text="Nom et coordonnées de l'organisme de médiation. L'adhésion à un service de médiation est OBLIGATOIRE pour vendre en ligne.", verbose_name='médiateur de la consommation')),
                ('terms_updated_at', models.DateField(blank=True, help_text='À changer quand le texte des CGV est modifié.', null=True, verbose_name='CGV mises à jour le')),
            ],
            options={
                'verbose_name': 'informations légales',
                'verbose_name_plural': 'informations légales',
            },
        ),
    ]
