# Generated by Django 6.0.7 on 2026-08-28 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_legalsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalsettings',
            name='data_retention',
            field=models.CharField(blank=True, help_text='Combien de temps vous gardez les messages et commandes après le dernier échange (ex. « 12 mois »). Affiché dans la politique de confidentialité.', max_length=100, verbose_name='durée de conservation des données'),
        ),
    ]
