# Generated by Django 6.0.7 on 2026-08-28 09:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_legalsettings_data_retention'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro', models.TextField(blank=True, help_text='La phrase sous le titre, en haut de la page. Deux lignes maximum pour rester lisible.', verbose_name="phrase d'accroche")),
                ('story', models.TextField(blank=True, help_text="Le récit principal. Laissez une ligne vide entre deux paragraphes : ils seront séparés à l'affichage.", verbose_name='votre histoire')),
                ('closing', models.TextField(blank=True, help_text="Le petit encart en bas de page. L'adresse de la boutique y est ajoutée automatiquement.", verbose_name='phrase de fin')),
            ],
            options={
                'verbose_name': 'page À propos',
                'verbose_name_plural': 'page À propos',
            },
        ),
        migrations.CreateModel(
            name='AboutValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(choices=[('flower', 'Fleur'), ('coffee', 'Tasse de café'), ('heart', 'Cœur'), ('sparkles', 'Étincelles'), ('gift', 'Cadeau'), ('leaf', 'Feuille')], default='heart', max_length=20, verbose_name='icône')),
                ('title', models.CharField(max_length=80, verbose_name='titre')),
                ('text', models.TextField(help_text='Une à deux phrases : les cartes sont côte à côte, un texte trop long les déséquilibre.', verbose_name='description')),
                ('order', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name="ordre d'affichage")),
                ('visible', models.BooleanField(default=True, verbose_name='affichée sur le site')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='catalog.aboutpage', verbose_name='page')),
            ],
            options={
                'verbose_name': 'valeur (page À propos)',
                'verbose_name_plural': 'valeurs (page À propos)',
                'ordering': ['order', 'id'],
            },
        ),
    ]
