# Generated by Django 6.0.7 on 2026-08-28 12:17

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


def transferer_les_tarifs(apps, schema_editor):
    """Recopie les tarifs de SiteSettings vers ShippingSettings.

    Sans cette étape, les montants réglés par la cliente disparaîtraient avec
    les colonnes supprimées juste après. On crée donc la nouvelle ligne AVANT
    la suppression, comme pour toute migration qui déplace des données.

    apps.get_model() et non un import direct : les modèles d'aujourd'hui ne
    portent déjà plus ces champs.
    """
    SiteSettings = apps.get_model("catalog", "SiteSettings")
    ShippingSettings = apps.get_model("catalog", "ShippingSettings")

    if ShippingSettings.objects.exists():
        return

    ancien = SiteSettings.objects.first()
    if ancien is None:
        # Aucune coordonnée saisie : la ligne sera créée à la volée par
        # l'admin, avec les valeurs par défaut du modèle.
        return

    ShippingSettings.objects.create(
        shipping_fee=ancien.shipping_fee,
        free_shipping_from=ancien.free_shipping_from,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_about_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_fee', models.DecimalField(decimal_places=2, default=Decimal('5.90'), help_text='Montant facturé pour une livraison à domicile. Le retrait en boutique reste toujours gratuit.', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='frais de livraison (€)')),
                ('free_shipping_from', models.DecimalField(blank=True, decimal_places=2, help_text="À partir de ce montant d'achat, la livraison est offerte. Laisser vide pour la facturer systématiquement.", max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='livraison offerte à partir de (€)')),
            ],
            options={
                'verbose_name': 'livraison',
                'verbose_name_plural': 'livraison',
            },
        ),
        # Les valeurs sont recopiées avant que les colonnes disparaissent.
        migrations.RunPython(
            transferer_les_tarifs,
            migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='free_shipping_from',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='shipping_fee',
        ),
    ]
