# Generated by Django 6.0.7 on 2026-08-31 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0026_shippingsettings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='relay_address',
            field=models.CharField(blank=True, max_length=200, verbose_name='adresse du point relais'),
        ),
        migrations.AddField(
            model_name='order',
            name='relay_city',
            field=models.CharField(blank=True, max_length=100, verbose_name='ville du point relais'),
        ),
        migrations.AddField(
            model_name='order',
            name='relay_id',
            field=models.CharField(blank=True, help_text='Numéro Mondial Relay du point, ex. FR-012345.', max_length=20, verbose_name='identifiant du point relais'),
        ),
        migrations.AddField(
            model_name='order',
            name='relay_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='nom du point relais'),
        ),
        migrations.AddField(
            model_name='order',
            name='relay_postal_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='code postal du point relais'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('pickup', 'Retrait en boutique'), ('home', 'Livraison à domicile'), ('relay', 'Livraison en point relais')], default='pickup', max_length=20, verbose_name='mode de livraison'),
        ),
    ]
