# Generated by Django 6.0.7 on 2026-08-31 15:25

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0027_order_relay_address_order_relay_city_order_relay_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingsettings',
            name='relay_shipping_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('4.50'), help_text="Montant facturé pour une livraison en point relais. Généralement moins cher qu'une livraison à domicile.", max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='frais en point relais (€)'),
        ),
    ]
