# Generated by Django 6.0.7 on 2026-09-01 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0028_shippingsettings_relay_shipping_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, help_text="Le numéro d'expédition Mondial Relay. Envoyé au client avec l'email d'expédition.", max_length=40, verbose_name='numéro de suivi'),
        ),
    ]
