# Generated by Django 6.0.7 on 2026-09-08 12:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0029_order_tracking_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutvalue',
            name='order',
            field=models.PositiveIntegerField(default=1, help_text="Le plus petit nombre s'affiche en premier (1 avant 2, 2 avant 3…).", validators=[django.core.validators.MinValueValidator(1)], verbose_name="ordre d'affichage"),
        ),
        migrations.AlterField(
            model_name='drinkofmonth',
            name='order',
            field=models.PositiveIntegerField(default=1, help_text="Le plus petit nombre s'affiche en premier (1 avant 2, 2 avant 3…).", validators=[django.core.validators.MinValueValidator(1)], verbose_name="ordre d'affichage"),
        ),
        migrations.AlterField(
            model_name='drinkofmonthsettings',
            name='available_until',
            field=models.DateField(blank=True, help_text="Affiche « Durée limitée jusqu'au … » sur la page coffee shop. Laisser vide pour ne pas annoncer de date de fin.", null=True, verbose_name="disponibles jusqu'au"),
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='order',
            field=models.PositiveIntegerField(default=1, help_text="Le plus petit nombre s'affiche en premier (1 avant 2, 2 avant 3…).", validators=[django.core.validators.MinValueValidator(1)], verbose_name="ordre d'affichage"),
        ),
        migrations.AlterField(
            model_name='instagramstory',
            name='order',
            field=models.PositiveIntegerField(default=1, help_text="Le plus petit nombre s'affiche en premier (1 avant 2, 2 avant 3…).", validators=[django.core.validators.MinValueValidator(1)], verbose_name="ordre d'affichage"),
        ),
        migrations.AlterField(
            model_name='menudrink',
            name='order',
            field=models.PositiveIntegerField(default=1, help_text="Le plus petit nombre s'affiche en premier (1 avant 2, 2 avant 3…).", validators=[django.core.validators.MinValueValidator(1)], verbose_name="ordre d'affichage"),
        ),
        migrations.AlterField(
            model_name='product',
            name='featured',
            field=models.BooleanField(default=False, help_text='Met le produit en avant dans la boutique (filtre « coups de cœur »).', verbose_name='coup de cœur'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, help_text="Laisser vide : il est créé automatiquement à partir du nom. Le modifier change l'adresse de la fiche produit.", max_length=140, unique=True, verbose_name='identifiant URL'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0, help_text="Nombre d'exemplaires disponibles. À 0, le produit s'affiche comme épuisé et ne peut plus être commandé.", verbose_name='stock'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='order',
            field=models.PositiveIntegerField(default=1, help_text="Le plus petit nombre s'affiche en premier (1 avant 2, 2 avant 3…).", validators=[django.core.validators.MinValueValidator(1)], verbose_name="ordre d'affichage"),
        ),
        migrations.AlterField(
            model_name='supplement',
            name='order',
            field=models.PositiveIntegerField(default=1, help_text="Le plus petit nombre s'affiche en premier (1 avant 2, 2 avant 3…).", validators=[django.core.validators.MinValueValidator(1)], verbose_name="ordre d'affichage"),
        ),
    ]
