# Generated by Django 6.0.7 on 2026-09-10 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0031_add_order_cancel_reason'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('must_change_password', models.BooleanField(default=False, help_text='Coché, la personne est invitée à choisir son propre mot de passe à sa prochaine connexion.', verbose_name='doit choisir un nouveau mot de passe')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL, verbose_name='compte')),
            ],
            options={
                'verbose_name': 'profil de compte',
                'verbose_name_plural': 'profils de compte',
            },
        ),
    ]
