# Generated by Django 6.0.7 on 2026-09-11 13:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0032_staffprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinkofmonth',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0)], verbose_name='prix (€)'),
        ),
        migrations.AlterField(
            model_name='menudrink',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0)], verbose_name='prix (€)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0)], verbose_name='prix (€)'),
        ),
        migrations.AlterField(
            model_name='supplement',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0)], verbose_name='prix (€)'),
        ),
    ]
