"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# En prod, la vraie clé vient de la variable d'environnement DJANGO_SECRET_KEY
# (définie sur Railway). En local, on retombe sur la clé de dev ci-dessous.
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-l_0uxex^9is*1#op=j*ecgnkaa^x62b9=mqp7m-=15t*&b555s",
)

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG est désactivé par défaut. On ne l'active QUE si DJANGO_DEBUG == "1".
# En local, mettre DJANGO_DEBUG=1 dans son environnement pour retrouver les
# pages d'erreur détaillées.
DEBUG = os.environ.get("DJANGO_DEBUG", "0") == "1"

# Les hôtes autorisés à servir le site, séparés par des virgules dans la
# variable d'env DJANGO_ALLOWED_HOSTS (ex: "cheriecherry.fr,www.cheriecherry.fr").
# En local (DEBUG), on autorise localhost automatiquement.
ALLOWED_HOSTS = [
    h.strip()
    for h in os.environ.get("DJANGO_ALLOWED_HOSTS", "").split(",")
    if h.strip()
]
if DEBUG:
    ALLOWED_HOSTS += ["127.0.0.1", "localhost"]

# URL du site public (le front Next.js), vers laquelle pointe le bouton
# « Voir le site » de l'admin. Elle change selon l'environnement, donc on la
# lit dans une variable d'env : en prod, mettre FRONTEND_URL sur le service
# backend (ex: "https://www.cheriecherry.fr"). En local, on retombe sur le
# serveur `npm run dev`.
FRONTEND_URL = os.environ.get("FRONTEND_URL", "http://localhost:3000")

# Jeton d'aperçu : ajouté à l'URL « Voir le site » quand le front est en mode
# « coming soon », pour que l'admin voie le VRAI site (les visiteurs voient
# toujours la page coming soon). Doit être IDENTIQUE au PREVIEW_TOKEN côté
# frontend (le proxy Next le vérifie). Vide par défaut → pas d'aperçu.
PREVIEW_TOKEN = os.environ.get("PREVIEW_TOKEN", "")

# Railway sert le site derrière un proxy HTTPS. Ces réglages disent à Django
# de faire confiance à l'en-tête envoyé par le proxy pour savoir qu'on est en
# HTTPS, et de n'accepter les requêtes POST de l'admin que depuis nos domaines.
CSRF_TRUSTED_ORIGINS = [
    o.strip()
    for o in os.environ.get("DJANGO_CSRF_TRUSTED_ORIGINS", "").split(",")
    if o.strip()
]
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Librairies tierces
    'rest_framework',
    # Nos apps
    'catalog',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise sert les fichiers statiques (le CSS de l'admin, etc.) en prod.
    # Doit être placé juste après SecurityMiddleware.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # Dossier de templates au niveau du projet, cherché AVANT ceux des apps.
        # C'est ce qui nous permet de surcharger admin/base_site.html (relooking
        # de l'admin + lien « Voir le site » en nouvel onglet).
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# En prod, Railway fournit une variable DATABASE_URL pointant vers Postgres.
# dj_database_url la traduit en config Django. En local, DATABASE_URL n'existe
# pas → on retombe sur le fichier SQLite comme avant.
DATABASES = {
    'default': dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

# Français : traduit automatiquement toute l'interface de l'admin.
LANGUAGE_CODE = 'fr-fr'

# Fuseau horaire de Paris (cohérent avec les horaires d'ouverture affichés).
TIME_ZONE = 'Europe/Paris'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# STATIC_ROOT : dossier où `collectstatic` rassemble tous les fichiers statiques
# (CSS/JS de l'admin Django, etc.) pour que WhiteNoise les serve en prod.
STATIC_ROOT = BASE_DIR / "staticfiles"

# WhiteNoise : compresse et met en cache les fichiers statiques.
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        # CompressedStaticFilesStorage : compresse les fichiers statiques sans
        # exiger un "manifest" strict. On évite ainsi le 500 si un fichier
        # référencé manque (le variant "Manifest..." plante dans ce cas).
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}


# Fichiers "media" = fichiers uploadés par les utilisateurs (images produits).
# MEDIA_URL  : l'URL publique sous laquelle on y accède (ex: /media/products/x.jpg)
# MEDIA_ROOT : le dossier réel sur le disque où Django les range.
#   - En local : backend/media/ (comme avant).
#   - En prod  : Railway définit DJANGO_MEDIA_ROOT vers un VOLUME persistant
#     (ex: /data/media) pour que les photos survivent aux redéploiements.
MEDIA_URL = "media/"
MEDIA_ROOT = os.environ.get("DJANGO_MEDIA_ROOT", BASE_DIR / "media")